# Generated by Django 2.1.5 on 2019-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190209_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
