# Generated by Django 2.1.5 on 2019-02-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190209_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmenu',
            old_name='link',
            new_name='link_name',
        ),
    ]
