# Generated by Django 2.1.5 on 2019-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190209_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название раздела меню'),
        ),
    ]
